- name: Enable lamp repo
  command: amazon-linux-extras enable lamp-mariadb10.2-php7.2=latest
  changed_when: false

- name: Installing mariadb and mariadb-server
  package:
    name:
      - mariadb
      - mariadb-server
    state: present

- name: Starting Mariadb Service
  service:
    name: mariadb
    state: started
    enabled: true

- meta: end_play
  when: create_db_and_db_user == false

- name: Create dabase user {{ database_user }}
  command: mysql -u root -e "CREATE USER '{{ database_user }}'@'{{ hostname }}' IDENTIFIED BY '{{ database_user_password }}';"
  ignore_errors: true


- name: Creating Database {{ database }}
  command: mysql -u root -e "CREATE DATABASE `{{ database }}`;"
  changed_when: false
  ignore_errors: true

- name: Grand All privilages on {{ database }} to {{ database_user }}
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON `{{ database }}`.* TO '{{ database_user }}'@'{{ hostname }}'; FLUSH PRIVILEGES;"
  changed_when: false
  ignore_errors: true
