- name: "{{ ansible_facts['os_family'] }}"
  include_vars: "{{ ansible_facts['os_family']  }}.yml"

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes
  when: ansible_facts['os_family'] == "Debian"

- name: Installing HTTPD packages
  package:
    name: "{{ webserver }}"
    state: present

- name: unarchive wordpress file
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: .
    remote_src: true

- name: move data to document root
  copy:
    src: wordpress/
    dest: /var/www/html
    remote_src: true

- name: copying worpress template
  template:
    src: wp-config.php
    dest: /var/www/html/wp-config.php

- include_tasks: amz_linux.yml
  when: ansible_facts['distribution'] == 'Amazon'

- name: "Install php in {{ ansible_facts['os_family'] }}"
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Starting Apache httpd service
  service:
    name: "{{ webserver }}"
    state: restarted
    enabled: true

